Add support for browser-sync

diff --git a/run b/run
--- a/run
+++ b/run
@@ -36,10 +36,10 @@ fi
 
 if [ $# -gt 0 ] && [ $1 = '-help' ]
 then
-    echo "Usage: start.sh (PHP web server will be listening to localhost:8082)"
-    echo "Usage: start.sh -remote (PHP web server will be listening to 0.0.0.0:8082 and accessible from the outside)"
-    echo "Usage: start.sh -tests (Run all the unit and functional tests and runs static analysis"
-    echo "Usage: start.sh -tests-server (Internal use — Run PHP web server listening to localhost:8083)"
+    echo "Usage: run (PHP web server will be listening to localhost:8082)"
+    echo "Usage: run -remote (PHP web server will be listening to 0.0.0.0:8082 and accessible from the outside)"
+    echo "Usage: run -tests (Run all the unit and functional tests and runs static analysis"
+    echo "Usage: run -tests-server (Internal use — Run PHP web server listening to localhost:8083)"
     echo "Additional parameters will be ignored."
     exit 1
 fi
@@ -58,4 +58,18 @@ case "$1" in
 esac
 
 echo -e $(tput setaf 2; tput bold)"Launching PHP development server (php -S ${SERVER} -t public/ app/inc/router.php)"$(tput sgr0)
+
+if command -v browser-sync &> /dev/null
+    then
+    echo "browser-sync could not be found"
+    browser-sync start --proxy "localhost:8082" --files "**/*" &
+fi
+
 php -S ${SERVER} -t public/ app/inc/router.php
+
+function ctrl_c() {
+    pkill browser-sync
+}
+
+# trap ctrl-c and call ctrl_c()
+trap ctrl_c INT
